displayName=Chat XL
author=1877
description=Resize the chatbox and its text for improved readability. [A.K.A. BBC - Big Bold Chat]
tags=1877,accessibility,bbc,big,bigger,bold,chat,chatbox,classic,fixed,font,fonts,large,magnifier,magnify,messages,modern,pm,private,readability,resizable,resize,resizer,resizing,scale,size,small,text,zoom
version=2.0.0
plugins=com.bigboldchat.ChatXL
build=standard