displayName=Chat XL
author=1877
description=Resize the chatbox and its text for improved readability. [A.K.A. BBC - Big Bold Chat]
tags=1877,bbc,big,bold,chat,chatbox,text,font,fonts,size,resize,resizer,resizable,magnify,magnifier,zoom,scale,large,bigger,small,readability,accessibility,private,pm,messages
version=1.0.0
plugins=com.chatmagnifier.ChatXL
build=standard